### ISSUE TITLE
Fix synapse.py testing

### ISSUE THREAD

**Issue by andrewelamb** [Sage-Bionetworks/schematic_db#6]
Currently tests for synapse.py are failing.

AC: Get Github testing workflow working for all modules

The testing Github action has been temporarily changed :
```
#with open('tests/data/synapse_config.yml', 'w', encoding="utf-8") as f:
          #  yaml.dump(f, yaml)
```
and

`- run: poetry run pytest tests/test_mysql.py`

Error:
```
Run import yaml
  import yaml
  data = {
    "username": "test",
    "auth_token": "test",
    "project_id": "syn3383[2](https://github.com/Sage-Bionetworks/schematic_db/runs/7636679211?check_suite_focus=true#step:4:2)4[3](https://github.com/Sage-Bionetworks/schematic_db/runs/7636679211?check_suite_focus=true#step:4:3)2"
  }
  with open('tests/data/synapse_config.yml', 'w', encoding="utf-8") as f:
    yaml.dump(f, yaml)
  shell: /usr/bin/python {0}
  env:
    SYNAPSE_LOGIN: ***
    SYNAPSE_AUTH_TOKEN: ***
Traceback (most recent call last):
  File "/home/runner/work/_temp/f9cb5562-[4](https://github.com/Sage-Bionetworks/schematic_db/runs/7636679211?check_suite_focus=true#step:4:4)7f9-467a-b2c2-f48866664491.py", line 8, in <module>
    yaml.dump(f, yaml)
  File "/usr/lib/python3/dist-packages/yaml/__init__.py", line 290, in dump
    return dump_all([data], stream, Dumper=Dumper, **kwds)
  File "/usr/lib/python3/dist-packages/yaml/__init__.py", line 278, in dump_all
    dumper.represent(data)
  File "/usr/lib/python3/dist-packages/yaml/representer.py", line 27, in represent
    node = self.represent_data(data)
  File "/usr/lib/python3/dist-packages/yaml/representer.py", line [5](https://github.com/Sage-Bionetworks/schematic_db/runs/7636679211?check_suite_focus=true#step:4:5)2, in represent_data
    node = self.yaml_multi_representers[data_type](self, data)
  File "/usr/lib/python3/dist-packages/yaml/representer.py", line 31[7](https://github.com/Sage-Bionetworks/schematic_db/runs/7636679211?check_suite_focus=true#step:4:7), in represent_object
    reduce = data.__reduce_ex__(2)
TypeError: cannot pickle '_io.TextIOWrapper' object
Error: Process completed with exit code 1.`
```

**Comment by milen-sage** [comment]
Any updates on this one?

**Comment by andrewelamb** [comment]
@milen-sage Please see the linked PR above.
